name: 'Create .env files'
description: 'Creates .env files for the backend and frontend'
inputs:
  backend_port:
    description: 'The backend port'
    required: true
  database_url:
    description: 'The database URL'
    required: true
  frontend_port:
    description: 'The frontend port'
    required: true
  backend_url:
    description: 'The backend URL'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Create .env for the backend
      shell: bash
      run: |
        echo "BACKEND_PORT=${{ inputs.backend_port }}" >> ./app/backend/.env
        echo "DATABASE_URL=${{ inputs.database_url }}" >> ./app/backend/.env
    
    - name: Create .env for the frontend
      shell: bash
      run: |
        echo "FRONTEND_PORT=${{ inputs.frontend_port }}" >> ./app/frontend/.env
        echo "REACT_APP_BACKEND_URL=${{ inputs.backend_url }}" >> ./app/frontend/.env