services:
  backend:
    build: ./backend/
    image: backend_image
    container_name: backend_container
    ports: 
      - "${BACKEND_PORT:-8000}:${BACKEND_PORT:-8000}"
    env_file:
      - ./backend/.env
  
  frontend:
    build: ./frontend/
    image: frontend_image
    container_name: frontend_container
    ports:
      - "${FRONTEND_PORT:-3000}:${FRONTEND_PORT:-3000}"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:${BACKEND_PORT:-8000}
    env_file:
      - ./backend/.env
      - ./frontend/.env
    depends_on:
      - backend