services:
  backend:
    build: ./backend/
    image: backend_image
    container_name: backend_container
    ports: 
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${BACKEND_PORT}/docs"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s
  
  frontend:
    build: ./frontend/
    image: frontend_image
    container_name: frontend_container
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    env_file:
      - .env
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:${BACKEND_PORT}
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${FRONTEND_PORT}"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s