services:
  backend:
    build: ./backend/
    image: backend_image
    container_name: backend_container
    ports: 
      - "8000:8000"
    env_file:
      - .env
  
  frontend:
    build: ./frontend/
    image: frontend_image
    container_name: frontend_container
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8000
    depends_on:
      - backend