# Parser constants
MIN_CITATION_COUNT_FILTER = 15
MIN_REFERENCE_COUNT_FILTER = 20
MIN_YEAR_FILTER = 1900
TEST_SET_YEAR = 2014

# Text vector constants
MIN_DOC_FREQ = 5

# Text embedding constants
BERT_MAX_TOKENS = 512
BATCH_SIZE = 32
NUM_WORKERS = 2

# Node embedding constants
NODE2VEC_DIM = 128
NODE2VEC_WALK_LEN = 80
NODE2VEC_NUM_WALKS = 200
NODE2VEC_WINDOW = 10
NODE2VEC_MIN_COUNT = 1
NODE2VEC_BATCH_WORDS = 4

# Fusion constants
CCA_DIM = 128
DCCA_TEXT_HIDDEN_LAYERS = [512, 256, CCA_DIM]
DCCA_NODE_HIDDEN_LAYERS = [CCA_DIM]
DCCA_EPOCHS = 100

# Rerank constants
PAGERANK_ALPHA = 0.85
HITS_MAX_ITER = 100
HITS_TOLERANCE = 1.0e-8
