# Parser constants
MIN_CITATION_COUNT_FILTER = 15
MIN_REFERENCE_COUNT_FILTER = 20
MIN_YEAR_FILTER = 1900
TEST_SET_YEAR = 2014

# Text vector constants
MIN_DOC_FREQ = 5

# Text embedding constants
BERT_MAX_TOKENS = 512
BATCH_SIZE = 32
NUM_WORKERS = 2

# Rerank constants
PAGERANK_ALPHA = 0.85
