# Environment constants
NUM_WORKERS = 2

# Parser constants
MIN_CITATION_COUNT_FILTER = 15
MIN_REFERENCE_COUNT_FILTER = 20
MIN_YEAR_FILTER = 1900
TEST_SET_YEAR = 2014

# Text embedding constants
MIN_DOC_FREQ = 5

BERT_MAX_TOKENS = 512
TEXT_EMBEDDING_BATCH_SIZE = 32
DOC2VEC_DIM = 300
DOC2VEC_WINDOW = 5

# Node embedding constants
NODE_EMBEDDING_DIM = 128
NODE_EMBEDDING_WALK_LEN = 80
NODE_EMBEDDING_NUM_WALKS = 200
NODE_EMBEDDING_WINDOW = 10
NODE_EMBEDDING_MIN_COUNT = 1
NODE_EMBEDDING_BATCH_WORDS = 4

# Fusion constants
CCA_DIM = 128

DCCA_TEXT_HIDDEN_LAYERS = [512, 256, 128]
DCCA_NODE_HIDDEN_LAYERS = [128]
DCCA_EPOCHS = 10
DCCA_BATCH_SIZE = 1024

# Rerank constants
PAGERANK_ALPHA = 0.85

HITS_MAX_ITER = 100
HITS_TOLERANCE = 1.0e-8
