name: Continuous Deployment

on:
  push:
    branches:
      - 'main'

env:
  TAG_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPO }}
  
jobs:
  docker-hub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Create .env files
        uses: ./.github/actions/create-env
        with:
          backend_port: ${{ secrets.BACKEND_PORT }}
          database_url: ${{ secrets.DATABASE_URL }}
          frontend_port: ${{ secrets.FRONTEND_PORT }}
          backend_url: ${{ secrets.BACKEND_URL }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push Docker images
        uses: docker/bake-action@v6
        with:
          push: true
          workdir: ./app
          files: |-
            ./app/docker-compose.yaml
            ./app/docker-compose-cache.json
          set: |
            backend.tags=${{ env.TAG_NAME }}:backend-latest
            frontend.tags=${{ env.TAG_NAME }}:frontend-latest