name: Continuous Deployment Pipeline

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  
jobs:
  docker-hub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Build Docker Compose services
        run: |
          docker compose -f ./app/docker-compose.yaml build
 
      - name: Tag Docker images
        run: |
          BACKEND_IMAGE="${{ secrets.DOCKERHUB_USERNAME }}/fyp-backend"
          FRONTEND_IMAGE="${{ secrets.DOCKERHUB_USERNAME }}/fyp-frontend"
          SHA_TAG="${GITHUB_SHA}"

          docker tag backend_image $BACKEND_IMAGE:$SHA_TAG
          docker tag frontend_image $FRONTEND_IMAGE:$SHA_TAG

          docker tag backend_image $BACKEND_IMAGE:latest
          docker tag frontend_image $FRONTEND_IMAGE:latest
        
      - name: Push Docker images to Docker Hub
        run: |
          docker push $BACKEND_IMAGE:$SHA_TAG
          docker push $FRONTEND_IMAGE:$SHA_TAG

          docker push $BACKEND_IMAGE:latest
          docker push $FRONTEND_IMAGE:latest
