name: Continuous Deployment Pipeline

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  
jobs:
  docker-hub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build Docker Compose services
        run: |
          docker compose -f ./app/docker-compose.yaml build

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/fyp:backend-latest
            ${{ secrets.DOCKERHUB_USERNAME }}/fyp:frontend-latest
