name: Continuous Integration

on:
  push:
    branches:
      - main
  
  pull_request:
    branches:
      - '*'

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'
          cache-dependency-path: |
            ./app/backend/requirements/requirements.txt
            ./app/backend/requirements/requirements.dev.txt

      - name: Install dependencies
        working-directory: ./app/backend/requirements
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt
          pip install --no-cache-dir -r requirements.dev.txt
      
      - name: Run linter
        working-directory: ./app/backend
        run: |
          flake8 .
      
      - name: Run tests
        working-directory: ./app/backend
        run: |
          pytest
        
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage-report
          path: ./app/backend/coverage.xml
  
  frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: ./app/frontend/package-lock.json
      
      - name: Install dependencies
        working-directory: ./app/frontend
        run: |
          npm install
      
      - name: Build app
        working-directory: ./app/frontend
        run: |
          npm run build
        
      - name: Run linter
        working-directory: ./app/frontend
        run: |
          npm run lint
      
      - name: Run tests
        working-directory: ./app/frontend
        run: |
          npm run test
      
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: frontend-coverage-report
          path: ./app/frontend/coverage/clover.xml
  
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build Docker images
        uses: docker/bake-action@v6
        with:
          push: false
          workdir: ./app
          files: |-
            ./app/docker-compose.yaml
            ./app/docker-compose-cache.json
  
  research:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'
          cache-dependency-path: |
            ./research/requirements/requirements.dev.txt
      
      - name: Install dependencies
        working-directory: ./research/requirements
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.dev.txt
      
      - name: Run linter
        working-directory: ./research
        run: |
          flake8 .