name: Continuous Integration

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'
          cache-dependency-path: |
            ./app/backend/requirements/base.txt
            ./app/backend/requirements/dev.txt
      
      - name: Install dependencies
        working-directory: ./app/backend/requirements
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r base.txt
          pip install --no-cache-dir -r dev.txt
      
      - name: Run linter
        working-directory: ./app/backend
        run: |
          flake8 .
      
      - name: Run tests
        working-directory: ./app/backend
        run: |
          pytest
        
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage-report
          path: ./app/backend/coverage.xml
  
  frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: ./app/frontend/package-lock.json
      
      - name: Install dependencies
        working-directory: ./app/frontend
        run: |
          npm install
      
      - name: Build app
        working-directory: ./app/frontend
        run: |
          npm run build
        
      - name: Run linter
        working-directory: ./app/frontend
        run: |
          npm run lint
      
      - name: Run tests
        working-directory: ./app/frontend
        run: |
          npm run test
      
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: frontend-coverage-report
          path: ./app/frontend/coverage/clover.xml
  
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v3
      
      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-
      
      - name: Build Docker Compose services
        run: |
          docker buildx bake --file ./app/docker-compose.yaml --file ./app/docker-compose-cache.json
  
  research:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'
          cache-dependency-path: |
            ./research/requirements/dev.txt
      
      - name: Install dependencies
        working-directory: ./research/requirements
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r dev.txt
      
      - name: Run linter
        working-directory: ./research
        run: |
          flake8 .